---
Name: thumbor_config
After:
  - '#assetsimage'
  - '#assetscore'
  - '#assetadmingraphql-dependencies'
  - '#assetadminthumbnails'
  - '#assetsfieldtypes'
  - '#assetadmin'
  - '#assetadminfield'
---
# Example configuration for creating images
Codem\Thumbor\Config:
  # from /etc/thumbor/thumbor.conf (MY_SECURE_KEY is the default, you shouldn't use this)
  thumbor_generation_key: 'override_this_in_your_project'
  # the key used to sign protected image urls, best to not use the generation key above
  signing_key: 'a >= 64 character key used to sign protected image urls'
  # a salt used in signing protected image urls
  salt: ''
  use_https : true
  expiry_time: 10
  # if serving off a directory
  backend_path : ''
  # In your project configuration, set your own backends
  # backends:
  #  - 'cdn1.example.com'
  # And some protected backends
  # Protected backends are used to serve protected assets
  # protected_backends:
  #  - 'protected1.example.com'
