---
Name: thumbor_config
---
# use our image class
Injector:
  Image:
    class: 'Codem\Thumbor\Image'
# store config for creating tags
Codem\Thumbor\Config:
  # from /etc/thumbor/thumbor.conf (MY_SECURE_KEY)
  thumbor_generation_key: 'MY_SECURE_KEY'
  backend_protocol_https : true
  # if serving off a directory
  backend_path : ''
  # list all backends here, as many as you want
  backends:
    - 'cdn1.example.com'
#Codem\Thumbor\Image:
#Codem\Thumbor\Image_Backend:
