---
Name: thumbor_crop_requirements
After:
    - '#assetsimage'
---
SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - 'codem/thumbylla: client/lib/cropperjs/dist/cropper.min.css'
    - 'codem/thumbylla: client/dist/css/main.css'
  extra_requirements_javascript:
    - 'codem/thumbylla: client/dist/js/main.js'
